name             'server-base'
maintainer       'Pulselocker, Inc.'
maintainer_email 'sean@pulselocker.com'
license          'Apache 2.0'
description      'Installs/Configures server-base'
long_description 'Installs/Configures server-base'
version          '1.2.1'
issues_url       'https://github.com/arktos65/server-base-cookbook/issues' if respond_to?(:issues_url)
source_url       'https://github.com/arktos65/server-base-cookbook' if respond_to?(:source_url)

recipe 'server-base', 'Default recipe installs all base packages for a Linux server.'
recipe 'server-base::system-common', 'Common packages and tools for Linux servers.'
recipe 'server-base::python-support', 'Installs Python 2.x environment.'
recipe 'server-base::ruby-support', 'Installs Ruby 2.x environment.'

depends 'apt'
depends 'openssh'
depends 'ntp'
depends 'rsyslog'
depends 'networking-basic'
depends 'build-essential'
depends 'ruby_build'
depends 'rake'
depends 'zip'
depends 'poise-python'
